//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnElectronics.Database.Recources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LearnElectronics_Database_ru_Test2_QuestionVariants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LearnElectronics_Database_ru_Test2_QuestionVariants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LearnElectronics.Database.Recources.LearnElectronics.Database.ru.Test2.QuestionVa" +
                            "riants", typeof(LearnElectronics_Database_ru_Test2_QuestionVariants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Электрон.
        /// </summary>
        internal static string Question1Variant1 {
            get {
                return ResourceManager.GetString("Question1Variant1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Протон.
        /// </summary>
        internal static string Question1Variant2 {
            get {
                return ResourceManager.GetString("Question1Variant2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нейтрон.
        /// </summary>
        internal static string Question1Variant3 {
            get {
                return ResourceManager.GetString("Question1Variant3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Позитрон.
        /// </summary>
        internal static string Question1Variant4 {
            get {
                return ResourceManager.GetString("Question1Variant4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Планетарная.
        /// </summary>
        internal static string Question2Variant1 {
            get {
                return ResourceManager.GetString("Question2Variant1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пуддинг с изюмом.
        /// </summary>
        internal static string Question2Variant2 {
            get {
                return ResourceManager.GetString("Question2Variant2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коаксиальная.
        /// </summary>
        internal static string Question2Variant3 {
            get {
                return ResourceManager.GetString("Question2Variant3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ядро.
        /// </summary>
        internal static string Question3Variant1 {
            get {
                return ResourceManager.GetString("Question3Variant1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Электроны.
        /// </summary>
        internal static string Question3Variant2 {
            get {
                return ResourceManager.GetString("Question3Variant2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Протоны.
        /// </summary>
        internal static string Question3Variant3 {
            get {
                return ResourceManager.GetString("Question3Variant3", resourceCulture);
            }
        }
    }
}
