//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnElectronics.Database.Recources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LearnElectronics_Database_ru_Test1_QuestionVariants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LearnElectronics_Database_ru_Test1_QuestionVariants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LearnElectronics.Database.Recources.LearnElectronics.Database.ru.Test1.QuestionVa" +
                            "riants", typeof(LearnElectronics_Database_ru_Test1_QuestionVariants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все то, что существует объективно.
        /// </summary>
        internal static string Question1Variant1 {
            get {
                return ResourceManager.GetString("Question1Variant1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вещество и поля которые существуют в пространстве.
        /// </summary>
        internal static string Question1Variant2 {
            get {
                return ResourceManager.GetString("Question1Variant2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Собирательный образ окружающей действительности.
        /// </summary>
        internal static string Question1Variant3 {
            get {
                return ResourceManager.GetString("Question1Variant3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Образы которые попадают на нашу сетчатку глаза.
        /// </summary>
        internal static string Question1Variant4 {
            get {
                return ResourceManager.GetString("Question1Variant4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид материи, образующий физический объект который не имеет массу.
        /// </summary>
        internal static string Question2Variant1 {
            get {
                return ResourceManager.GetString("Question2Variant1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Газ без цвета и запаха.
        /// </summary>
        internal static string Question2Variant2 {
            get {
                return ResourceManager.GetString("Question2Variant2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Множетсва, характеризуемые набором операций над элементами этого множества.
        /// </summary>
        internal static string Question2Variant3 {
            get {
                return ResourceManager.GetString("Question2Variant3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Непрерывность и однородность.
        /// </summary>
        internal static string Question3Variant1 {
            get {
                return ResourceManager.GetString("Question3Variant1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нестабильность и прерывистость.
        /// </summary>
        internal static string Question3Variant2 {
            get {
                return ResourceManager.GetString("Question3Variant2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Постоянность и последовательность.
        /// </summary>
        internal static string Question3Variant3 {
            get {
                return ResourceManager.GetString("Question3Variant3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неосязаемость и неоднородность.
        /// </summary>
        internal static string Question3Variant4 {
            get {
                return ResourceManager.GetString("Question3Variant4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид материи, который составляет физические объекты и имеет массу.
        /// </summary>
        internal static string Question4Variant1 {
            get {
                return ResourceManager.GetString("Question4Variant1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Совокупность атомов образующие физическое тело.
        /// </summary>
        internal static string Question4Variant2 {
            get {
                return ResourceManager.GetString("Question4Variant2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Одно из состояния материи.
        /// </summary>
        internal static string Question4Variant3 {
            get {
                return ResourceManager.GetString("Question4Variant3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дискретность и неоднородность.
        /// </summary>
        internal static string Question5Variant1 {
            get {
                return ResourceManager.GetString("Question5Variant1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Практичность и эфективность.
        /// </summary>
        internal static string Question5Variant2 {
            get {
                return ResourceManager.GetString("Question5Variant2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Целостность и совместимость.
        /// </summary>
        internal static string Question5Variant3 {
            get {
                return ResourceManager.GetString("Question5Variant3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Элементарная частица.
        /// </summary>
        internal static string Question6Variant1 {
            get {
                return ResourceManager.GetString("Question6Variant1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Атом.
        /// </summary>
        internal static string Question6Variant2 {
            get {
                return ResourceManager.GetString("Question6Variant2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Молекула.
        /// </summary>
        internal static string Question6Variant3 {
            get {
                return ResourceManager.GetString("Question6Variant3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вещество.
        /// </summary>
        internal static string Question6Variant4 {
            get {
                return ResourceManager.GetString("Question6Variant4", resourceCulture);
            }
        }
    }
}
